version: '3.9'

services:
  api:
    container_name: "rally-api"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT
      - JWT_SECRET_KEY
      - JWT_EXPIRES_IN
      - MONGO_URI
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - web-proxy 

networks:   
    web-proxy:
        external: true
        name: reverse-proxy
