name: Deploy to Self-Hosted

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PORT: ${{ secrets.PORT }}
  JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
  JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}
  MONGO_URI: ${{ secrets.MONGO_URI }}

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Copy repository
        uses: actions/checkout@v3

      - name: Build the docker-compose stack
        run: docker compose up -d --build

      - name: Clear all docker unused cache
        run: docker system prune -af
